# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

* Build a system of equations from given problem by creating matrix and vectors in NumPy
* Calculate the inverse and dot-product to get the values for unknown variables.
* Solve linear equations using `numpy.linalg.solve()`

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [8]:
import numpy as np

# Solution:
A = np.array([[29,41], [23,41]])
B = np.array([490,448]).T
print(A)
print(B)

inv_A = np.linalg.inv(A)
print(inv_A)

X = inv_A.dot(B)
print(X)


print(A.dot(X))

# Verify the answer linalg.solve()
np.linalg.solve(A,B.T)

[[29 41]
 [23 41]]
[490 448]
[[ 0.16666667 -0.16666667]
 [-0.09349593  0.11788618]]
[7. 7.]
[490. 448.]


array([7., 7.])

In [13]:
# Explain your answer in terms of prices
# 7 for both  coffee and tea

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in another music concert. 

How much was the admission for each child and adult?

In [9]:
# Create a system of equations

# Solution:
A = np.array([[12,3], [8,3]])
B = np.array([162,122]).T
print(A)
print(B)

inv_A = np.linalg.inv(A)
print(inv_A)

X = inv_A.dot(B)
print(X)


print(A.dot(X))

# Verify the answer linalg.solve()
np.linalg.solve(A,B.T)

[[12  3]
 [ 8  3]]
[162 122]
[[ 0.25       -0.25      ]
 [-0.66666667  1.        ]]
[10. 14.]
[162. 122.]


array([10., 14.])

In [7]:
# Describe your result
# 10 per child 14 per adult

## Exercise 3

You want to make a soup containing tomatoes, carrots and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost .75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables is in your soup.

In [1]:
# Create a system of equations
# x tomatoe, y onion, z carrot
# x + y + z = 7
# x = 2 y => x - 2y = 0
# x*Px + y*Py + z*Pz = 5.25
# .75 x + .5 y + 1.25 z = 5.25
# Py = .5
# Px = .75
# Pz = 1.25
# Solution:
A = np.array([[1,1,1], [1,-2,0], [.75,]])
B = np.array([162,122]).T
print(A)
print(B)

inv_A = np.linalg.inv(A)
print(inv_A)

X = inv_A.dot(B)
print(X)


print(A.dot(X))

# Verify the answer linalg.solve()
np.linalg.solve(A,B.T)


In [2]:
# Explain your answer


## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom , and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price, and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [3]:
# Create a system of equations


In [11]:
# Explain your answer


## Summary
In this lab, you learned how to use Numpy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `.solve()`. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 